### ISSUE TITLE
Blender 3.6 and 4.0

### ISSUE THREAD

**Issue by hansnolte** [Aodaruma/coa_tools2#20]
Hi Aodaruma,

Great that you take care of the COA tools.

Unfortunately they don't work on Blender 3.6 and 4.0 under Windows 10 with a GTX 1070 and the latest Studio Driver.

To test, I used the included stip.json from the Samples folder.
The error message is the same for both versions of Blender:

File "E:\Blender-3.6-SSGI\scripts\addons\coa_tools2\operators\import_sprites.py", line 281, in execute
    ).sprite_import_export_scale
AttributeError: 'COATools2Preferences' object has no attribute 'sprite_import_export_scale'

Nothing is imported and nothing else happens.

Bye Hans

P.S. Please can you make a Checkbox to deactivate the COA Tools-Updater in the Blender Prefs.

**Comment by tozpeak** [comment]
Hi Hans,

I'm not Aodaruma, but a potential contributor.

Seems like this plugin is in WIP state now. I got the same output at 3.3.11 LTS, and I'll try to fix it there.
Original ndee's tools can't be even turn on there, so there are some improvements.

If I get any successful run of COA Tools before I reach Aodaruma, I'll create a fork and call you to check it out. But I hope this repo to become the new main one.

**Comment by tozpeak** [comment]
I've fixed this issue, but it seems like Weight painting doesn't work. You can check [my version here](https://github.com/tozpeak/coa_tools2/tree/tozpeak/develop), until [my PR](https://github.com/Aodaruma/coa_tools2/pull/21) is merged.

**Comment by Aodaruma** [comment]
thank you for sending issue and PR! i'll check PR soon and merge it

**Comment by Aodaruma** [comment]
I noticed this bug and fixed it with https://github.com/Aodaruma/coa_tools2/commit/975145ae6329ae978aa1ab75008412e8679af5eb, but apparently forgot to merge it into the master branch.
I didn't add the description to that commit, so I'll merge the PR

**Comment by Aodaruma** [comment]
merged #21 and checked it works

**Comment by Aodaruma** [comment]
i opened the feature request to add checkbox to enable/disable the COA Tools-Updater at #22

**Comment by hansnolte** [comment]
Hi Aodaruma and tozpeak,
thank you very much for this super fast fix.
Both versions of you now work with Blender 3.6.
In Blender 4.0 from Today, only a Plane without material (texture) is imported and then this error message appears

`Error: Python: Traceback (most recent call last):
  File "E:\Blender\scripts\addons\coa_tools2\operators\import_sprites.py", line 305, in execute
    bpy.ops.coa_tools2.import_sprite(
  File "E:\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "E:\Blender\scripts\addons\coa_tools2\operators\import_sprites.py", line 463, in execute
    mat = self.create_material(context, obj.data, name=img.name)
  File "E:\Blender\scripts\addons\coa_tools2\operators\import_sprites.py", line 408, in create_material
    bpy.ops.coa_tools2.create_material_group()
  File "E:\Blender\4.0\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "E:\Blender\scripts\addons\coa_tools2\operators\import_sprites.py", line 193, in execute
    self.create_coa_material_group()
  File "E:\Blender\scripts\addons\coa_tools2\operators\import_sprites.py", line 140, in create_coa_material_group
    self.create_sockets(group_tree)
  File "E:\Blender\scripts\addons\coa_tools2\operators\import_sprites.py", line 96, in create_sockets
    if input_socket["label"] not in group_tree.inputs:
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'
Location: E:\Blender\4.0\scripts\modules\bpy\ops.py:109
Location: E:\Blender\4.0\scripts\modules\bpy\ops.py:109`
![Blender-4](https://github.com/Aodaruma/coa_tools2/assets/7922627/1ed76dbb-0dca-4e00-aaa8-a7d3ef5e64eb)



Next I'll see if it works with Krita and then I'll look for some good tutorials.

Thank you again to both of you!
Hans

**Comment by tozpeak** [comment]
Hi! Thank you for your report!
If anything will be wrong with Krita, please, report this as a separate issue.

I have a very raw fix for GIMP on modern Linux systems (works only with 2.99 beta). I haven't checked original GIMP script on Windows, but on Linux it has some Python dependency issues. If you need GIMP 2.99 solution, reach me, but I'll try to not forget to polish it a bit and push.

I think, I can support of Krita exporter as well. But you may try the way Krita -> GIMP -> Blender COA Tools.
Aodaruma mentioned his first priorities as documenting the plugin's code itself and Photoshop exporter, so I think, I'll take some hot-fixing FOSS integrations on me.
